- name: Adding aliases
  loop: "{{ aliases | dict2items }}"
  lineinfile:
    path: /etc/hosts
    line: "{{ item.value }} {{ item.key }}"

- name: Add zip's password to the wordlist
  lineinfile:
      path: /usr/share/wordlists/fasttrack.txt
      line: IhateMyJob

- name: Remove wordlists
  file:
      path: "/usr/share/wordlists/{{ item }}"
      state: absent
  with_items:
    -  dirb 
    -  dirbuster
    -  fern-wifi
    -  metasploit 
    -  nmap.lst 
    -  wfuzz 
    -  rockyou.txt.gz 


- name: Copy file fcrackzip with owner and permissions 
  copy:
      src: ../files/fcrackzip_1.0-10_amd64.deb
      dest: /tmp/fcrackzip_1.0-10_amd64.deb
      owner: root
      mode: '0644'

- name: Install fcrackzip deb package
  apt:
      deb: /tmp/fcrackzip_1.0-10_amd64.deb
